---
general:
  buildTool: "mta"
  verbose: true
service:
  buildToolVersion: "MBTJ21N20"
  stages:
    Release:
      cfCredentialsId: "cfdeploy"
stages:
  Build:
    mavenExecuteStaticCodeChecks: false
    npmExecuteLint: false
  Acceptance:
    cloudFoundryDeploy: false
    npmExecuteEndToEndTests: false
  Malware Scan:
    malwareExecuteScan: false
  Release:
    tmsExport: false
    tmsUpload: false
    cfApiEndpoint: "https://api.cf.eu10-004.hana.ondemand.com"
    cfOrg: "abat AG_abat-intern-spielwiese-cf-fsb"
    cfSpace: "dev"
    deployType: "standard"
    cloudFoundryDeploy: true
  Additional Unit Tests:
    npmExecuteScripts: false
  Compliance:
    sonarExecuteScan: false
steps:
  cloudFoundryDeploy:
    mtaDeployParameters: "-f --version-rule ALL"
  artifactPrepareVersion:
    versioningType: "cloud_noTag"
  mtaBuild:
    applicationName: "MyApplication"
    buildTarget: "CF"
    platform: "CF"
